import type { Metadata } from "next";
import { PolicyDocument, PolicyHeading, PolicyLink } from "@/components/phase3/policies/policy-layout";

export const metadata: Metadata = {
  title: { absolute: "Lovemind | Terms and Conditions" },
};

export default function TermsPage() {
  return (
    <PolicyDocument title="Terms and Conditions">
      <PolicyHeading>Agreement between User and Lovemind.net</PolicyHeading>
      <p>Welcome to lovemind.net. The lovemind.net website (the “Site”) is comprised of various webpages operated by Lovemind Inc (“Lovemind”). Lovemind.net is offered to you conditioned on your acceptance without modification of the terms, conditions, and notices contained herein (the “Terms”). Your use of lovemind.net constitutes your agreement to all such Terms. Please read these terms carefully, and keep a copy of them for your reference.</p>
      <p>Lovemind.net is an E-Commerce Site.</p>
      <p>The purpose of lovemind.net is to provide tutoring services for all ages of clientele as well as to sell any related merchandise.</p>

      <PolicyHeading>Privacy</PolicyHeading>
      <p>Your use of lovemind.net is subject to Lovemind’s Privacy Policy. Please review our Privacy Policy, which also governs the Site and informs users of our data collection practices.</p>

      <PolicyHeading>Electronic Communications</PolicyHeading>
      <p>Visiting lovemind.net or sending emails to Lovemind constitutes electronic communications. You consent to receive electronic communications and you agree that all agreements, notices, disclosures and other communications that we provide to you electronically, via email and on the Site, satisfy any legal requirement that such communications be in writing.</p>

      <PolicyHeading>Your Account</PolicyHeading>
      <p>If you use this site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. You may not assign or otherwise transfer your account to any other person or entity. You acknowledge that Lovemind is not responsible for their party access to your account that results from theft or misappropriation of your account. Lovemind and its associates reserve the right to refuse or cancel service, terminate accounts, or remove or edit content in our sole discretion.</p>

      <PolicyHeading>Children Under Thirteen</PolicyHeading>
      <p>Lovemind does not knowingly collect, either online or offline, personal information form persons under the age of thirteen, If you are under 18, you may use lovemind.net only with permission of a parent or guardian.</p>

      <PolicyHeading>Cancelation/Refund Policy</PolicyHeading>
      <p>You may request to cancel your ticket for a full refund, up to 72 hours before the date and time of the event. Cancellations between 25-72 hours before the event may transferred to a different date/time of the same service. Cancellation requests made within 24 hours of the service date/time may not receive a refund nor a transfer. When you register for a service, you agree to these terms.</p>

      <PolicyHeading>Fulfillment and Shipping Policy</PolicyHeading>
      <p>Your use of lovemind.net is subject to Lovemind’s Fulfillment and Shipping Policy. Please review our Fulfillment and Shipping Policy, which also governs the Site.</p>

      <PolicyHeading>Links to Third-Party Sites/Third-Party Services</PolicyHeading>
      <p>lovemind.net may contain links to other websites (“Linked Sites”). The Linked Sites are not under the control of Lovemind and Lovemind is not responsible for the contents of any Linked Site, including without limitation any link contained in a Linked Site, or any changes or updates to any Linked Site. Lovemind is providing these links to you only as a convenience, and the includion of any link does not imploy endorsement by Lovemind of the site or any association with its operators.</p>
      <p>Certain services made available via lovemind.net are delivered by third-party sites and organizations. By using any product, service or functionality originating from the lovemind.net domain, you hereby acknowledge and consent that Lovemind may share such information and data with any third-party with whom Lovemind has a contractual relationship to provide the requested product, service or functionality on behalf of lovemind.net users and customers.</p>

      <PolicyHeading>No Unlawful or Prohibited Use/Intellectual Property</PolicyHeading>
      <p>You are granted a non-exclusive, non-transferable, revocable license to access and use lovemind.net strictly in accordance with these terms of use. As a condition of your use of the Site, you warrant to Lovemind that you will not use the Site for any purpose that is unlawful or prohibited by these Terms. You may not use the Site in any manner which could damage, disable, overburden, or impair the Site or interfere with any other party’s use and enjoyment of the Site. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available or provided for through the Site.</p>
      <p>All content included as part of the Service, such as text, graphics, logos, images, as well as the compilation thereof, and any software used on the site, is property of Lovemind or its suppliers and protected by copyright and other laws that protect intellectual property and proprietary rights. You agree to observe and abide by all copyright and other proprietary notices, legends or other restrictions contained in any such content and will not make any changes thereto.</p>
      <p>You will not modify, publish, transmit, reverse engineer, participate in the transfer or sale, create derivative works, or in any way exploit any of the content, in whole or in party, found on the Site. Lovemind content is not for resale. Your use of the Site does not entitle you to make any unauthorized use of any protected content, and in particular you will not delete or alter any proprietary right or attribution notices in any content. You will use protected content solely for your personal use, and will make no other use of the content without the express written permission of Lovemind and the copyright owner. You agree that you do not acquire any ownership right in any protected content. We do not grant you any licenses, express or implied, to the intellectual property of Lovemind or our licensors except as expressly authorized by these Terms.</p>

      <PolicyHeading>Use of Communication Services</PolicyHeading>
      <p>The Site may contain bulletin board services, chat areas, news groups, forums, communities, personal web pages, calendars, and/or other message or communications facilities designed to enable you to communicate with the public at large or with a group (collectively, “Communications Services”). You agree to use the Communication Services only to post, send and receive messages and material that are proper and related to the particular Communication Service.</p>
      <p>By way of example, and not as a limitation, you agree that when using a Communication Service, you will not: defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others; publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, name, material or information; upload files that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless you own or control the rights thereto or have received all necessary consents; upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another&apos;s computer; advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Service specifically allows such messages; conduct or forward surveys, contests, pyramid schemes or chain letters; download any file posted by another user of a Communication Service that you know, or reasonably should know, cannot be legally distributed in such manner; falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded; restrict or inhibit any other user from using and enjoying the Communication Services; violate any code of conduct or other guidelines which may be applicable for any particular Communication Service; harvest or otherwise collect information about others, including e-mail addresses, without their consent; violate any applicable laws or regulations.</p>
      <p>Lovemind has no obligation to monitor the Communication Services. However, Lovemind reserves the right to review materials posted to a Communication Service and to remove any materials in its sole discretion. Lovemind reserves the right to terminate your access to any or all of the Communication Services at any time without notice for any reason whatsoever.</p>
      <p>Lovemind reserves the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or govermnental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in Lovemind&apos;s sole discretion.</p>
      <p>Always use caution when giving out any personally identifying information about yourself or your children in any Communication Service. Lovemind does not control or endorse the content, messages or information found in any Communication Service and, therefore, Lovemind specifically disclaims any liability with regard to the Communication Services and any actions resulting from your participation in any Communication Service. Managers and hosts are not authorized Lovemind spokespersons, and their views do not necessarily reflect those of Lovemind.</p>
      <p>Materials uploaded to a Communication Service may be subject to posted limitations on usage, reproduction and/or dissemination. You are responsible for adhering to such limitations if you upload the materials.</p>

      <PolicyHeading>Materials Provided to lovemind.net or Posted on Any Lovemind Web Page</PolicyHeading>
      <p>Lovemind does not claim ownership of the materials you provide to lovemind.net (including feedback and suggestions) or post, upload, input or submit to any Lovemind Site or our associated services (collectively &quot;Submissions&quot;). However, by posting, uploading, inputting, providing or submitting your Submission you are granting Lovemind, our affiliated companies and necessary sublicensees permission to use your Submission in connection with the operation of their Internet businesses including, without limitation, the rights to: copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat your Submission; and to publish your name in connection with your Submission.</p>
      <p>No compensation will be paid with respect to the use of your Submission, as provided herein. Lovemind is under no obligation to post or use any Submission you may provide and may remove any Submission at any time in Lovemind&apos;s sole discretion.</p>
      <p>By posting, uploading, inputting, providing or submitting your Submission you warrant and represent that you own or otherwise control all of the rights to your Submission as described in this section including, without limitation, all the rights necessary for you to provide, post, upload, input or submit the Submissions.</p>

      <PolicyHeading>Third-Party Accounts</PolicyHeading>
      <p>You will be able to connect your Lovemind account to third-party accounts. By connecting your Lovemind account to your third-party account, you acknowledge and agree that you are consenting to the continuous release of information about you to others (in accordance with your privacy settings on those third-party sites). If you do not want information about you to be shared in this manner, do not use this feature.</p>

      <PolicyHeading>International Users</PolicyHeading>
      <p>The Service is controlled, operated and administered by Lovemind from our offices within the USA. If you access the Service from a location outside the USA, you are responsible for compliance with all local laws. You agree that you will not use the Lovemind Content accessed through lovemind.net in any country or in any manner prohibited by any applicable laws, restrictions or regulations.</p>

      <PolicyHeading>Indemnification</PolicyHeading>
      <p>You agree to indemnify, defend and hold harmless Lovemind, its officers, directors, employees, agents and third-parties, for any losses, costs, liabilities and expenses (including reasonable attorney&apos;s fees) relating to or arising out of your use of or inability to use the Site or services, any user postings made by you, your violation of any terms of this Agreement or your violation of any rights of a third-party, or your violation of any applicable laws, rules or regulations. Lovemind reserves the right, at its own cost, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with Lovemind in asserting any available defenses.</p>

      <PolicyHeading>Class Action Waiver</PolicyHeading>
      <p>Any arbitration under these Terms and Conditions will take place on an individual basis; class arbitrations and class/representative/collective actions are not permitted. THE PARTIES AGREE THAT A PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN EACH’S INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PUTATIVE CLASS, COLLECTIVE AND/ OR REPRESENTATIVE PROCEEDING, SUCH AS IN THE FORM OF A PRIVATE ATTORNEY GENERAL ACTION AGAINST THE OTHER. Further, unless both you and Lovemind agree otherwise, the arbitrator may not consolidate more than one person&apos;s claims, and may not otherwise preside over any form of a representative or class proceeding.</p>

      <PolicyHeading>Liability Disclaimer</PolicyHeading>
      <p>THE INFORMATION, SOFTWARE, PRODUCTS, AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THE SITE MAY INCLUDE INACCURACIES OR TYPOGRAPHICAL ERRORS. CHANGES ARE PERIODICALLY ADDED TO THE INFORMATION HEREIN. LOVEMIND INC AND/OR ITS SUPPLIERS MAY MAKE IMPROVEMENTS AND/OR CHANGES IN THE SITE AT ANY TIME.</p>
      <p>LOVEMIND INC AND/OR ITS SUPPLIERS MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, AND ACCURACY OF THE INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS CONTAINED ON THE SITE FOR ANY PURPOSE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ALL SUCH INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS ARE PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OR CONDITION OF ANY KIND. LOVEMIND INC AND/OR ITS SUPPLIERS HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH REGARD TO THIS INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS, INCLUDING ALL IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.</p>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL LOVEMIND INC AND/OR ITS SUPPLIERS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF USE, DATA OR PROFITS, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OR PERFORMANCE OF THE SITE, WITH THE DELAY OR INABILITY TO USE THE SITE OR RELATED SERVICES, THE PROVISION OF OR FAILURE TO PROVIDE SERVICES, OR FOR ANY INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS OBTAINED THROUGH THE SITE, OR OTHERWISE ARISING OUT OF THE USE OF THE SITE, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF LOVEMIND INC OR ANY OF ITS SUPPLIERS HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. BECAUSE SOME STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SITE, OR WITH ANY OF THESE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SITE.</p>

      <PolicyHeading>Termination/Access Restriction</PolicyHeading>
      <p>Lovemind reserves the right, in its sole discretion, to terminate your access to the Site and the related services or any portion thereof at any time, without notice. To the maximum extent permitted by law, this agreement is governed by the laws of the State of Colorado and you hereby consent to the exclusive jurisdiction and venue of courts in Colorado in all disputes arising out of or relating to the use of the Site. Use of the Site is unauthorized in any jurisdiction that does not give effect to all provisions of these Terms, including, without limitation, this section.</p>
      <p>You agree that no joint venture, partnership, employment, or agency relationship exists between you and Lovemind as a result of this agreement or use of the Site. Lovemind&apos;s performance of this agreement is subject to existing laws and legal process, and nothing contained in this agreement is in derogation of Lovemind&apos;s right to comply with govermnental, court and law enforcement requests or requirements relating to your use of the Site or information provided to or gathered by Lovemind with respect to such use. If any part of this agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the agreement shall continue in effect.</p>
      <p>Unless otherwise specified herein, this agreement constitutes the entire agreement between the user and Lovemind with respect to the Site and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between the user and Lovemind with respect to the Site. A printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. It is the express wish to the parties that this agreement and all related documents be written in English.</p>

      <PolicyHeading>Changes to Terms</PolicyHeading>
      <p>Lovemind reserves the right, in its sole discretion, to change the Terms under which lovemind.net is offered. The most current version of the Terms will supersede all previous versions. Lovemind encourages you to periodically review the Terms to stay informed of our updates.</p>

      <PolicyHeading>Contact Us</PolicyHeading>
      <p>Lovemind welcomes your questions or comments regarding the Terms:</p>
      <p>Lovemind Inc</p>
      <p>Email Address:</p>
      <p><PolicyLink href="mailto:contact@lovemind.net?subject=Terms%20%26%20Conditions%20Support">contact@lovemind.net</PolicyLink></p>
      <p>Effective as of January 20, 2020</p>
    </PolicyDocument>
  );
}
